# Page settings
baseurl = "localhost:1313"
title = "HUGO TEST"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Hugo Test"
    services = "Services"
    resources = "Resources"
    signup = "Sign Up"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Welcome to Hugo."
    subtitle = 'Show off your HTML and CSS skills through Hugo'
    text = 'Make sure you follow the documentation'
    button = 'Good Luck'

  # Clients
  [params.clients]
    [[params.clients.item]]
      img = "tedx.png"
    [[params.clients.item]]
      img = "tedx.png"
    [[params.clients.item]]
      img = "tedx.png"
    [[params.clients.item]]
      img = "tedx.png"


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Lorem Ipsum is dummy text for the printing and typesetting industry"
      icon = "icon-briefcase"
      to = "20,000+"

    [[params.counters.item]]
      description = "Lorem Ipsum is dummy text for the printing and typesetting industry"
      icon = "icon-code"
      to = "900M+"

    [[params.counters.item]]
      description = "Lorem Ipsum is dummy text for the printing and typesetting industry"
      icon = "icon-cup"
      to = "100%"

    [[params.counters.item]]
      description = "Lorem Ipsum is dummy text for the printing and typesetting industry"
      icon = "icon-people"
      to = "1,000+"  
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Messaging solutions for every role"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Sales &amp; Marketing"
      description = "Lorem Ipsum is simply dummy text for the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Communications"
      description = "Lorem Ipsum is simply dummy text for the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Operations"
      description = "Lorem Ipsum is simply dummy text for the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
      icon = "icon-video2"

      [[params.services.item]]
      title = "Development"
      description = "Lorem Ipsum is simply dummy text for the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."    
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
